replicaCount: 1

image:
  repository: ghcr.io/kiukairor/pulse-shell
  pullPolicy: IfNotPresent
  tag: "sha-f071df5"

imagePullSecrets:
  - name: ghcr-secret

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: pulse.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

env:
  NEW_RELIC_APP_NAME: "pulse-pulse-shell"
  HOSTNAME: "0.0.0.0"
  PORT: "3000"
  NEXT_PUBLIC_FEED_MFE_URL: "https://pulse.test:30443/_mfe/feed"
  NEXT_PUBLIC_PROFILE_MFE_URL: "https://pulse.test:30443/_mfe/profile"
  NEXT_PUBLIC_EVENT_SVC_URL: "https://pulse.test:30443/api/event-svc"
  NEXT_PUBLIC_AI_SVC_URL: "https://pulse.test:30443/api/ai-svc"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"

secrets:
  newrelic: newrelic-secret
  postgres: postgres-secret
  redis: redis-secret
  anthropic: anthropic-secret
  app: app-secret
