image:
  repository: ghcr.io/kiukairor/sync-events
  pullPolicy: IfNotPresent
  tag: "sha-313b05b"

imagePullSecrets:
  - name: ghcr-secret

schedule: "0 0 * * *"

secrets:
  postgres: postgres-secret
  ticketmaster: ticketmaster-secret
