image:
  repository: ghcr.io/kiukairor/sync-events
  pullPolicy: IfNotPresent
  tag: "sha-bc36e9a"

imagePullSecrets:
  - name: ghcr-secret

schedule: "0 0 * * *"

env:
  GEMINI_MODEL: "gemini-3.1-flash-lite-preview"

secrets:
  postgres: postgres-secret
  gemini: gemini-secret
