replicaCount: 1

image:
  repository: ghcr.io/kiukairor/test-svc
  pullPolicy: IfNotPresent
  tag: "sha-13366fa"

imagePullSecrets:
  - name: ghcr-secret

service:
  type: ClusterIP
  port: 8090

env:
  PORT: "8090"
  GEMINI_MODEL: "gemini-3.1-flash-lite-preview"
  NEW_RELIC_APP_NAME: "dontask"
  NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
  NEW_RELIC_APPLICATION_LOGGING_ENABLED: "true"
  NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED: "true"
  NEW_RELIC_AI_MONITORING_ENABLED: "true"
  NEW_RELIC_AI_MONITORING_STREAMING_ENABLED: "true"
  NEW_RELIC_AI_MONITORING_RECORD_CONTENT_ENABLED: "true"
  NEW_RELIC_SPAN_EVENTS_MAX_SAMPLES_STORED: "10000"

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "200m"

secrets:
  gemini: gemini-secret
  newrelic: newrelic-secret
